In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.preprocessing import StandardScaler
import time
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import RidgeClassifier
#from sklearn.naive_bayes import GaussianNB -- cannot be used in RFE
#from sklearn.neighbors import KNeighborsClassifier  -- cannot be used in RFE

In [8]:
##Independent variable - x ; Dependent variable- y; Number of featues - n/k
  #NB &  KNN -- cannot be used in FeatureImportance

def FI(x,y,n):

    FIlist=[]   
    #scaler = StandardScaler()
    #x = pd.DataFrame(scaler.fit_transform(x), columns=x.columns)

    RF=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    RF.fit(x, y) 
    
    LR=LogisticRegression(solver='saga',max_iter=1000, random_state=42)
    LR.fit(x, y)  
    
    DT=DecisionTreeClassifier(criterion='gini',max_features='sqrt',splitter='best',random_state=0)
    DT.fit(x, y)
    
    SV=SVC(kernel='linear',random_state=0)
    SV.fit(x, y)

    gbm = XGBClassifier(n_estimators=50, random_state=42) ## or GradientBoostingClassifier
    gbm.fit(x, y)
   
    ridge = RidgeClassifier()
    ridge.fit(x, y)

    
    # Combine results into a single comparison DataFrame
    importance_comparison = pd.DataFrame({
        "Feature": x.columns,
        "Random_Forest_MDI": RF.feature_importances_,
        "Decision Tree": DT.feature_importances_,
        "SV": abs(SV.coef_[0]),
        "Gradient_Boosting_MDI": gbm.feature_importances_,
        "LR_Coefficients": abs(LR.coef_[0]),  # Using absolute values for magnitude
        "Ridge_Coefficients": abs(ridge.coef_[0]),  # Using absolute values for magnitude
    })

    print(importance_comparison.to_string(index=False))
    
    for i in ["Random_Forest_MDI","Decision Tree","SV","Gradient_Boosting_MDI", "LR_Coefficients","Ridge_Coefficients"]:
        
        top_n_features = importance_comparison.sort_values(by=i, ascending=False)['Feature'].head(n).tolist()
        FIlist.append(top_n_features)
        print(FIlist)
    return FIlist
    



def split_scalar(x,y):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)
    
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    
    from sklearn.metrics import classification_report
    report=classification_report(y_test,y_pred)
    
    from sklearn.metrics import accuracy_score
    Accuracy=accuracy_score(y_test,y_pred)
    
    return classifier,Accuracy,report,x_test,y_test,cm

def logistic(x_train,y_train,x_test):
    from sklearn.linear_model import LogisticRegression
    classifier=LogisticRegression(random_state=0)
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def svm_linear(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='linear',random_state=0)
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def svm_NL(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='rbf',random_state=0)
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def Navie(x_train,y_train,x_test):
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def knn(x_train,y_train,x_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def decision(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def random(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10 , criterion='entropy', random_state=0)
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,x_test,y_test,cm

def FI_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf):
    dataframe=pd.DataFrame(index=['RF','DT','SVM','XGB','LogR','Ridge'],columns=['Logistic','SVMl','SVMnl','KNN','Naive','Decision','Random'])
    for number, index in enumerate(dataframe.index):
        #print("number, index",number, index)
        dataframe['Logistic'][index]=acclog[number]
        dataframe['SVMl'][index]=accsvml[number]
        dataframe['SVMnl'][index]=accsvmnl[number]
        dataframe['KNN'][index]=accknn[number]
        dataframe['Naive'][index]=accnav[number]
        dataframe['Decision'][index]=accdes[number]
        dataframe['Random'][index]=accrf[number]
    return dataframe

In [9]:
dataset1=pd.read_csv('watson_healthcare_modified.csv',index_col=None)
df2=dataset1
df2

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,3,Technical Degree,1,...,2,80,0,1,3,1,1,0,0,0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,3,Marketing,1,...,3,80,1,15,3,3,3,2,1,2
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,3,Life Sciences,1,...,4,80,0,1,0,4,1,0,0,0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,1,Life Sciences,1,...,3,80,1,21,3,3,21,6,11,8
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,2,Medical,1,...,2,80,0,9,5,2,8,7,0,7

In [13]:
df2=pd.get_dummies(df2,drop_first=True)
##df2['Attrition']
df2.columns

Index(['EmployeeID', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'Shift', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition_Yes',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Maternity', 'Department_Neurology',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Male',
       'JobRole_Administrative', 'JobRole_Nurse', 'JobRole_Other',
       'JobRole_Therapist', 'MaritalStatus_Married', 'MaritalStatus_Single',
       'OverTime_Yes'],
      dtype='object')

In [14]:
x=df2.drop('Attrition_Yes',axis=1)
y=df2['Attrition_Yes']

In [25]:
FIlist=FI(x,y,35)
FIlist

/Users/Max/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

                         Feature  Random_Forest_MDI  Decision Tree           SV  Gradient_Boosting_MDI  LR_Coefficients  Ridge_Coefficients
                      EmployeeID           0.045932       0.045341 1.342178e+00               0.010952     9.096401e-07        3.369904e-08
                             Age           0.078719       0.033150 7.754098e+02               0.045164     6.696990e-07        1.196202e-02
                       DailyRate           0.033167       0.056619 4.400900e+02               0.014938     9.635666e-06        3.899130e-05
                DistanceFromHome           0.042601       0.063690 5.895505e+02               0.024823     2.077980e-07        7.407592e-03
                       Education           0.012645       0.013599 1.541482e+01               0.010235     2.027739e-08        4.402326e-03
                   EmployeeCount           0.000000       0.000000 1.890044e-12               0.000000     4.095256e-09        0.000000e+00
         EnvironmentSatisfaction           0.031034       0.013915 7.440163e+01               0.028340     4.546999e-08        7.288933e-02
                      HourlyRate           0.031161       0.045097 4.066276e+02               0.015879     4.897832e-07        1.120744e-03
                  JobInvolvement           0.026939       0.025623 7.101830e+01               0.027506     4.890772e-08        1.351754e-01
                        JobLevel           0.036067       0.006402 8.219129e+00               0.079747     4.414364e-08        3.352620e-02
                 JobSatisfaction           0.020443       0.023885 8.483134e+01               0.020200     3.942425e-08        5.908072e-02
                   MonthlyIncome           0.076485       0.073579 1.185505e+02               0.052596     1.522205e-04        7.741807e-08
                     MonthlyRate           0.037854       0.065070 1.630489e+01               0.015511     1.242193e-05        2.871936e-06
              NumCompaniesWorked           0.042458       0.032237 8.128833e+01               0.026718     1.588667e-08        2.423841e-02
               PercentSalaryHike           0.023592       0.021098 4.935651e+01               0.014000     6.016379e-08        7.773473e-04
               PerformanceRating           0.002072       0.000000 2.832057e+00               0.000000     1.180432e-08        1.471886e-02
        RelationshipSatisfaction           0.018048       0.028744 3.440168e+01               0.015762     1.710776e-08        2.105627e-02
                   StandardHours           0.000000       0.000000 1.518856e-10               0.000000     3.276205e-07        0.000000e+00
                           Shift           0.022414       0.027008 7.385300e+01               0.046911     4.415275e-08        4.220141e-02
               TotalWorkingYears           0.041642       0.025046 3.008170e+02               0.049954     4.085825e-07        5.709964e-03
           TrainingTimesLastYear           0.020139       0.035044 5.810988e+01               0.014005     3.304988e-08        1.312277e-02
                 WorkLifeBalance           0.021829       0.002255 3.540046e+01               0.025655     2.912113e-08        6.943226e-02
                  YearsAtCompany           0.048788       0.085650 2.780301e+02               0.036764     2.994114e-07        6.026917e-04
              YearsInCurrentRole           0.020783       0.007299 2.249758e+02               0.020720     2.013359e-07        1.358324e-02
         YearsSinceLastPromotion           0.021148       0.034328 1.718379e+01               0.023959     5.518693e-08        1.617713e-02
            YearsWithCurrManager           0.027937       0.027386 1.997632e+02               0.024730     1.909242e-07        1.341651e-02
BusinessTravel_Travel_Frequently           0.007309       0.022160 2.597564e+01               0.016974     9.385722e-09        1.487188e-01
    BusinessTravel_Travel_Rarely           0.010159       0.008482 1.922228e+01               0.010220     1.041050e-08        2.055364e-02
            Department_Maternity           0.008661       0.003801 1.814358e+01               0.031900     4.035772e-09        4.660302e-02
            Department_Neurology           0.003573       0.013228 2.024363e+00               0.041992     6.709410e-09        1.675462e-02
    EducationField_Life Sciences           0.006551       0.017282 1.832057e+00               0.005051     1.911974e-09        1.389616e-01
        EducationField_Marketing           0.003170       0.003801 1.316794e+01               0.008980     3.642604e-09        9.455263e-02
          EducationField_Medical           0.004831       0.000950 2.000000e+01               0.027711     7.257463e-09        1.943440e-01
            EducationField_Other           0.001321       0.007487 4.000000e+00               0.000000     1.457898e-09        2.062500e-01
 EducationField_Technical Degree           0.001945       0.008430 7.000000e+00               0.000000     1.411927e-09        7.839183e-02
                     Gender_Male           0.007679       0.000000 1.877772e+01               0.003336     6.031868e-09        1.017414e-02
          JobRole_Administrative           0.000804       0.003801 1.369986e+00               0.000000     2.911038e-09        4.071085e-02
                   JobRole_Nurse           0.007162       0.011404 9.756368e-01               0.014101     4.907973e-10        1.195639e-01
                   JobRole_Other           0.008800       0.004888 9.394349e+00               0.004504     7.994347e-09        9.896543e-02
               JobRole_Therapist           0.004424       0.000000 9.000000e+00               0.011446     9.175857e-09        2.135404e-01
           MaritalStatus_Married           0.006621       0.006238 2.957518e+01               0.015738     1.851496e-08        2.109617e-02
            MaritalStatus_Single           0.026237       0.040900 4.857518e+01               0.040218     2.665550e-08        2.047379e-01
                    OverTime_Yes           0.106856       0.055081 9.342482e+01               0.122759     4.519593e-08        4.903251e-01
[['OverTime_Yes', 'Age', 'MonthlyIncome', 'YearsAtCompany', 'EmployeeID', 'DistanceFromHome', 'NumCompaniesWorked', 'TotalWorkingYears', 'MonthlyRate', 'JobLevel', 'DailyRate', 'HourlyRate', 'EnvironmentSatisfaction', 'YearsWithCurrManager', 'JobInvolvement', 'MaritalStatus_Single', 'PercentSalaryHike', 'Shift', 'WorkLifeBalance', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'TrainingTimesLastYear', 'RelationshipSatisfaction', 'Education', 'BusinessTravel_Travel_Rarely', 'JobRole_Other', 'Department_Maternity', 'Gender_Male', 'BusinessTravel_Travel_Frequently', 'JobRole_Nurse', 'MaritalStatus_Married', 'EducationField_Life Sciences', 'EducationField_Medical', 'JobRole_Therapist']]
[['OverTime_Yes', 'Age', 'MonthlyIncome', 'YearsAtCompany', 'EmployeeID', 'DistanceFromHome', 'NumCompaniesWorked', 'TotalWorkingYears', 'MonthlyRate', 'JobLevel', 'DailyRate', 'HourlyRate', 'EnvironmentSatisfaction', 'YearsWithCurrManager', 'JobInvolvement', 'MaritalStatus_Single', 'PercentSalaryHike', 'Shift', 'WorkLifeBalance', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'TrainingTimesLastYear', 'RelationshipSatisfaction', 'Education', 'BusinessTravel_Travel_Rarely', 'JobRole_Other', 'Department_Maternity', 'Gender_Male', 'BusinessTravel_Travel_Frequently', 'JobRole_Nurse', 'MaritalStatus_Married', 'EducationField_Life Sciences', 'EducationField_Medical', 'JobRole_Therapist'], ['YearsAtCompany', 'MonthlyIncome', 'MonthlyRate', 'DistanceFromHome', 'DailyRate', 'OverTime_Yes', 'EmployeeID', 'HourlyRate', 'MaritalStatus_Single', 'TrainingTimesLastYear', 'YearsSinceLastPromotion', 'Age', 'NumCompaniesWorked', 'RelationshipSatisfaction', 'YearsWithCurrManager', 'Shift', 'JobInvolvement', 'TotalWorkingYears', 'JobSatisfaction', 'BusinessTravel_Travel_Frequently', 'PercentSalaryHike', 'EducationField_Life Sciences', 'EnvironmentSatisfaction', 'Education', 'Department_Neurology', 'JobRole_Nurse', 'BusinessTravel_Travel_Rarely', 'EducationField_Technical Degree', 'EducationField_Other', 'YearsInCurrentRole', 'JobLevel', 'MaritalStatus_Married', 'JobRole_Other', 'EducationField_Marketing', 'JobRole_Administrative']]
[['OverTime_Yes', 'Age', 'MonthlyIncome', 'YearsAtCompany', 'EmployeeID', 'DistanceFromHome', 'NumCompaniesWorked', 'TotalWorkingYears', 'MonthlyRate', 'JobLevel', 'DailyRate', 'HourlyRate', 'EnvironmentSatisfaction', 'YearsWithCurrManager', 'JobInvolvement', 'MaritalStatus_Single', 'PercentSalaryHike', 'Shift', 'WorkLifeBalance', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'TrainingTimesLastYear', 'RelationshipSatisfaction', 'Education', 'BusinessTravel_Travel_Rarely', 'JobRole_Other', 'Department_Maternity', 'Gender_Male', 'BusinessTravel_Travel_Frequently', 'JobRole_Nurse', 'MaritalStatus_Married', 'EducationField_Life Sciences', 'EducationField_Medical', 'JobRole_Therapist'], ['YearsAtCompany', 'MonthlyIncome', 'MonthlyRate', 'DistanceFromHome', 'DailyRate', 'OverTime_Yes', 'EmployeeID', 'HourlyRate', 'MaritalStatus_Single', 'TrainingTimesLastYear', 'YearsSinceLastPromotion', 'Age', 'NumCompaniesWorked', 'RelationshipSatisfaction', 'YearsWithCurrManager', 'Shift', 'JobInvolvement', 'TotalWorkingYears', 'JobSatisfaction', 'BusinessTravel_Travel_Frequently', 'PercentSalaryHike', 'EducationField_Life Sciences', 'EnvironmentSatisfaction', 'Education', 'Department_Neurology', 'JobRole_Nurse', 'BusinessTravel_Travel_Rarely', 'EducationField_Technical Degree', 'EducationField_Other', 'YearsInCurrentRole', 'JobLevel', 'MaritalStatus_Married', 'JobRole_Other', 'EducationField_Marketing', 'JobRole_Administrative'], ['Age', 'DistanceFromHome', 'DailyRate', 'HourlyRate', 'TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsWithCurrManager', 'MonthlyIncome', 'OverTime_Yes', 'JobSatisfaction', 'NumCompaniesWorked', 'EnvironmentSatisfaction', 'Shift', 'JobInvolvement', 'TrainingTimesLastYear', 'PercentSalaryHike', 'MaritalStatus_Single', 'WorkLifeBalance', 'RelationshipSatisfaction', 'MaritalStatus_Married', 'BusinessTravel_Travel_Frequently', 'EducationField_Medical', 'BusinessTravel_Travel_Rarely', 'Gender_Male', 'Department_Maternity', 'YearsSinceLastPromotion', 'MonthlyRate', 'Education', 'EducationField_Marketing', 'JobRole_Other', 'JobRole_Therapist', 'JobLevel', 'EducationField_Technical Degree', 'EducationField_Other']]
[['OverTime_Yes', 'Age', 'MonthlyIncome', 'YearsAtCompany', 'EmployeeID', 'DistanceFromHome', 'NumCompaniesWorked', 'TotalWorkingYears', 'MonthlyRate', 'JobLevel', 'DailyRate', 'HourlyRate', 'EnvironmentSatisfaction', 'YearsWithCurrManager', 'JobInvolvement', 'MaritalStatus_Single', 'PercentSalaryHike', 'Shift', 'WorkLifeBalance', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'TrainingTimesLastYear', 'RelationshipSatisfaction', 'Education', 'BusinessTravel_Travel_Rarely', 'JobRole_Other', 'Department_Maternity', 'Gender_Male', 'BusinessTravel_Travel_Frequently', 'JobRole_Nurse', 'MaritalStatus_Married', 'EducationField_Life Sciences', 'EducationField_Medical', 'JobRole_Therapist'], ['YearsAtCompany', 'MonthlyIncome', 'MonthlyRate', 'DistanceFromHome', 'DailyRate', 'OverTime_Yes', 'EmployeeID', 'HourlyRate', 'MaritalStatus_Single', 'TrainingTimesLastYear', 'YearsSinceLastPromotion', 'Age', 'NumCompaniesWorked', 'RelationshipSatisfaction', 'YearsWithCurrManager', 'Shift', 'JobInvolvement', 'TotalWorkingYears', 'JobSatisfaction', 'BusinessTravel_Travel_Frequently', 'PercentSalaryHike', 'EducationField_Life Sciences', 'EnvironmentSatisfaction', 'Education', 'Department_Neurology', 'JobRole_Nurse', 'BusinessTravel_Travel_Rarely', 'EducationField_Technical Degree', 'EducationField_Other', 'YearsInCurrentRole', 'JobLevel', 'MaritalStatus_Married', 'JobRole_Other', 'EducationField_Marketing', 'JobRole_Administrative'], ['Age', 'DistanceFromHome', 'DailyRate', 'HourlyRate', 'TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsWithCurrManager', 'MonthlyIncome', 'OverTime_Yes', 'JobSatisfaction', 'NumCompaniesWorked', 'EnvironmentSatisfaction', 'Shift', 'JobInvolvement', 'TrainingTimesLastYear', 'PercentSalaryHike', 'MaritalStatus_Single', 'WorkLifeBalance', 'RelationshipSatisfaction', 'MaritalStatus_Married', 'BusinessTravel_Travel_Frequently', 'EducationField_Medical', 'BusinessTravel_Travel_Rarely', 'Gender_Male', 'Department_Maternity', 'YearsSinceLastPromotion', 'MonthlyRate', 'Education', 'EducationField_Marketing', 'JobRole_Other', 'JobRole_Therapist', 'JobLevel', 'EducationField_Technical Degree', 'EducationField_Other'], ['OverTime_Yes', 'JobLevel', 'MonthlyIncome', 'TotalWorkingYears', 'Shift', 'Age', 'Department_Neurology', 'MaritalStatus_Single', 'YearsAtCompany', 'Department_Maternity', 'EnvironmentSatisfaction', 'EducationField_Medical', 'JobInvolvement', 'NumCompaniesWorked', 'WorkLifeBalance', 'DistanceFromHome', 'YearsWithCurrManager', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'BusinessTravel_Travel_Frequently', 'HourlyRate', 'RelationshipSatisfaction', 'MaritalStatus_Married', 'MonthlyRate', 'DailyRate', 'JobRole_Nurse', 'TrainingTimesLastYear', 'PercentSalaryHike', 'JobRole_Therapist', 'EmployeeID', 'Education', 'BusinessTravel_Travel_Rarely', 'EducationField_Marketing', 'EducationField_Life Sciences']]
[['OverTime_Yes', 'Age', 'MonthlyIncome', 'YearsAtCompany', 'EmployeeID', 'DistanceFromHome', 'NumCompaniesWorked', 'TotalWorkingYears', 'MonthlyRate', 'JobLevel', 'DailyRate', 'HourlyRate', 'EnvironmentSatisfaction', 'YearsWithCurrManager', 'JobInvolvement', 'MaritalStatus_Single', 'PercentSalaryHike', 'Shift', 'WorkLifeBalance', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'TrainingTimesLastYear', 'RelationshipSatisfaction', 'Education', 'BusinessTravel_Travel_Rarely', 'JobRole_Other', 'Department_Maternity', 'Gender_Male', 'BusinessTravel_Travel_Frequently', 'JobRole_Nurse', 'MaritalStatus_Married', 'EducationField_Life Sciences', 'EducationField_Medical', 'JobRole_Therapist'], ['YearsAtCompany', 'MonthlyIncome', 'MonthlyRate', 'DistanceFromHome', 'DailyRate', 'OverTime_Yes', 'EmployeeID', 'HourlyRate', 'MaritalStatus_Single', 'TrainingTimesLastYear', 'YearsSinceLastPromotion', 'Age', 'NumCompaniesWorked', 'RelationshipSatisfaction', 'YearsWithCurrManager', 'Shift', 'JobInvolvement', 'TotalWorkingYears', 'JobSatisfaction', 'BusinessTravel_Travel_Frequently', 'PercentSalaryHike', 'EducationField_Life Sciences', 'EnvironmentSatisfaction', 'Education', 'Department_Neurology', 'JobRole_Nurse', 'BusinessTravel_Travel_Rarely', 'EducationField_Technical Degree', 'EducationField_Other', 'YearsInCurrentRole', 'JobLevel', 'MaritalStatus_Married', 'JobRole_Other', 'EducationField_Marketing', 'JobRole_Administrative'], ['Age', 'DistanceFromHome', 'DailyRate', 'HourlyRate', 'TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsWithCurrManager', 'MonthlyIncome', 'OverTime_Yes', 'JobSatisfaction', 'NumCompaniesWorked', 'EnvironmentSatisfaction', 'Shift', 'JobInvolvement', 'TrainingTimesLastYear', 'PercentSalaryHike', 'MaritalStatus_Single', 'WorkLifeBalance', 'RelationshipSatisfaction', 'MaritalStatus_Married', 'BusinessTravel_Travel_Frequently', 'EducationField_Medical', 'BusinessTravel_Travel_Rarely', 'Gender_Male', 'Department_Maternity', 'YearsSinceLastPromotion', 'MonthlyRate', 'Education', 'EducationField_Marketing', 'JobRole_Other', 'JobRole_Therapist', 'JobLevel', 'EducationField_Technical Degree', 'EducationField_Other'], ['OverTime_Yes', 'JobLevel', 'MonthlyIncome', 'TotalWorkingYears', 'Shift', 'Age', 'Department_Neurology', 'MaritalStatus_Single', 'YearsAtCompany', 'Department_Maternity', 'EnvironmentSatisfaction', 'EducationField_Medical', 'JobInvolvement', 'NumCompaniesWorked', 'WorkLifeBalance', 'DistanceFromHome', 'YearsWithCurrManager', 'YearsSinceLastPromotion', 'YearsInCurrentRole', 'JobSatisfaction', 'BusinessTravel_Travel_Frequently', 'HourlyRate', 'RelationshipSatisfaction', 'MaritalStatus_Married', 'MonthlyRate', 'DailyRate', 'JobRole_Nurse', 'TrainingTimesLastYear', 'PercentSalaryHike', 'JobRole_Therapist', 'EmployeeID', 'Education', 'BusinessTravel_Travel_Rarely', 'EducationField_Marketing', 'EducationField_Life Sciences'], ['MonthlyIncome', 'MonthlyRate', 'DailyRate', 'EmployeeID', 'Age', 'HourlyRate', 'TotalWorkingYears', 'StandardHours', 'YearsAtCompany', 'DistanceFromHome', 'YearsInCurrentRole', 'YearsWithCurrManager', 'PercentSalaryHike', 'YearsSinceLastPromotion', 'JobInvolvement', 'EnvironmentSatisfaction', 'OverTime_Yes', 'Shift', 'JobLevel', 'JobSatisfaction', 'TrainingTimesLastYear', 'WorkLifeBalance', 'MaritalStatus_Single', 'Education', 'MaritalStatus_Married', 'RelationshipSatisfaction', 'NumCompaniesWorked', 'PerformanceRating', 'BusinessTravel_Travel_Rarely', 'BusinessTravel_Travel_Frequently', 'JobRole_Therapist', 'JobRole_Other', 'EducationField_Medical', 'Department_Neurology', 'Gender_Male']]

[['OverTime_Yes',
  'Age',
  'MonthlyIncome',
  'YearsAtCompany',
  'EmployeeID',
  'DistanceFromHome',
  'NumCompaniesWorked',
  'TotalWorkingYears',
  'MonthlyRate',
  'JobLevel',
  'DailyRate',
  'HourlyRate',
  'EnvironmentSatisfaction',
  'YearsWithCurrManager',
  'JobInvolvement',
  'MaritalStatus_Single',
  'PercentSalaryHike',
  'Shift',
  'WorkLifeBalance',
  'YearsSinceLastPromotion',
  'YearsInCurrentRole',
  'JobSatisfaction',
  'TrainingTimesLastYear',
  'RelationshipSatisfaction',
  'Education',
  'BusinessTravel_Travel_Rarely',
  'JobRole_Other',
  'Department_Maternity',
  'Gender_Male',
  'BusinessTravel_Travel_Frequently',
  'JobRole_Nurse',
  'MaritalStatus_Married',
  'EducationField_Life Sciences',
  'EducationField_Medical',
  'JobRole_Therapist'],
 ['YearsAtCompany',
  'MonthlyIncome',
  'MonthlyRate',
  'DistanceFromHome',
  'DailyRate',
  'OverTime_Yes',
  'EmployeeID',
  'HourlyRate',
  'MaritalStatus_Single',
  'TrainingTimesLastYear',
  'YearsSinceLastPromotion',
  'Age',
  'NumCompaniesWorked',
  'RelationshipSatisfaction',
  'YearsWithCurrManager',
  'Shift',
  'JobInvolvement',
  'TotalWorkingYears',
  'JobSatisfaction',
  'BusinessTravel_Travel_Frequently',
  'PercentSalaryHike',
  'EducationField_Life Sciences',
  'EnvironmentSatisfaction',
  'Education',
  'Department_Neurology',
  'JobRole_Nurse',
  'BusinessTravel_Travel_Rarely',
  'EducationField_Technical Degree',
  'EducationField_Other',
  'YearsInCurrentRole',
  'JobLevel',
  'MaritalStatus_Married',
  'JobRole_Other',
  'EducationField_Marketing',
  'JobRole_Administrative'],
 ['Age',
  'DistanceFromHome',
  'DailyRate',
  'HourlyRate',
  'TotalWorkingYears',
  'YearsAtCompany',
  'YearsInCurrentRole',
  'YearsWithCurrManager',
  'MonthlyIncome',
  'OverTime_Yes',
  'JobSatisfaction',
  'NumCompaniesWorked',
  'EnvironmentSatisfaction',
  'Shift',
  'JobInvolvement',
  'TrainingTimesLastYear',
  'PercentSalaryHike',
  'MaritalStatus_Single',
  'WorkLifeBalance',
  'RelationshipSatisfaction',
  'MaritalStatus_Married',
  'BusinessTravel_Travel_Frequently',
  'EducationField_Medical',
  'BusinessTravel_Travel_Rarely',
  'Gender_Male',
  'Department_Maternity',
  'YearsSinceLastPromotion',
  'MonthlyRate',
  'Education',
  'EducationField_Marketing',
  'JobRole_Other',
  'JobRole_Therapist',
  'JobLevel',
  'EducationField_Technical Degree',
  'EducationField_Other'],
 ['OverTime_Yes',
  'JobLevel',
  'MonthlyIncome',
  'TotalWorkingYears',
  'Shift',
  'Age',
  'Department_Neurology',
  'MaritalStatus_Single',
  'YearsAtCompany',
  'Department_Maternity',
  'EnvironmentSatisfaction',
  'EducationField_Medical',
  'JobInvolvement',
  'NumCompaniesWorked',
  'WorkLifeBalance',
  'DistanceFromHome',
  'YearsWithCurrManager',
  'YearsSinceLastPromotion',
  'YearsInCurrentRole',
  'JobSatisfaction',
  'BusinessTravel_Travel_Frequently',
  'HourlyRate',
  'RelationshipSatisfaction',
  'MaritalStatus_Married',
  'MonthlyRate',
  'DailyRate',
  'JobRole_Nurse',
  'TrainingTimesLastYear',
  'PercentSalaryHike',
  'JobRole_Therapist',
  'EmployeeID',
  'Education',
  'BusinessTravel_Travel_Rarely',
  'EducationField_Marketing',
  'EducationField_Life Sciences'],
 ['MonthlyIncome',
  'MonthlyRate',
  'DailyRate',
  'EmployeeID',
  'Age',
  'HourlyRate',
  'TotalWorkingYears',
  'StandardHours',
  'YearsAtCompany',
  'DistanceFromHome',
  'YearsInCurrentRole',
  'YearsWithCurrManager',
  'PercentSalaryHike',
  'YearsSinceLastPromotion',
  'JobInvolvement',
  'EnvironmentSatisfaction',
  'OverTime_Yes',
  'Shift',
  'JobLevel',
  'JobSatisfaction',
  'TrainingTimesLastYear',
  'WorkLifeBalance',
  'MaritalStatus_Single',
  'Education',
  'MaritalStatus_Married',
  'RelationshipSatisfaction',
  'NumCompaniesWorked',
  'PerformanceRating',
  'BusinessTravel_Travel_Rarely',
  'BusinessTravel_Travel_Frequently',
  'JobRole_Therapist',
  'JobRole_Other',
  'EducationField_Medical',
  'Department_Neurology',
  'Gender_Male'],
 ['OverTime_Yes',
  'JobRole_Therapist',
  'EducationField_Other',
  'MaritalStatus_Single',
  'EducationField_Medical',
  'BusinessTravel_Travel_Frequently',
  'EducationField_Life Sciences',
  'JobInvolvement',
  'JobRole_Nurse',
  'JobRole_Other',
  'EducationField_Marketing',
  'EducationField_Technical Degree',
  'EnvironmentSatisfaction',
  'WorkLifeBalance',
  'JobSatisfaction',
  'Department_Maternity',
  'Shift',
  'JobRole_Administrative',
  'JobLevel',
  'NumCompaniesWorked',
  'MaritalStatus_Married',
  'RelationshipSatisfaction',
  'BusinessTravel_Travel_Rarely',
  'Department_Neurology',
  'YearsSinceLastPromotion',
  'PerformanceRating',
  'YearsInCurrentRole',
  'YearsWithCurrManager',
  'TrainingTimesLastYear',
  'Age',
  'Gender_Male',
  'DistanceFromHome',
  'TotalWorkingYears',
  'Education',
  'HourlyRate']]

In [26]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [27]:
for i in FIlist:
    
    df=x[i]
    
    x_train,x_test,y_train,y_test=split_scalar(df,y)

    classifier,Accuracy,report,x_test,y_test,cm=logistic(x_train,y_train,x_test)
    acclog.append(Accuracy)

    classifier,Accuracy,report,x_test,y_test,cm=svm_linear(x_train,y_train,x_test)
    accsvml.append(Accuracy)

    classifier,Accuracy,report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)
    accsvmnl.append(Accuracy)

    classifier,Accuracy,report,x_test,y_test,cm=Navie(x_train,y_train,x_test)
    accnav.append(Accuracy)

    classifier,Accuracy,report,x_test,y_test,cm=knn(x_train,y_train,x_test)
    accknn.append(Accuracy)

    classifier,Accuracy,report,x_test,y_test,cm=decision(x_train,y_train,x_test)
    accdes.append(Accuracy)

    classifier,Accuracy,report,x_test,y_test,cm=random(x_train,y_train,x_test)
    accrf.append(Accuracy)

In [28]:
result=FI_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [ ]:
##result # n=5

In [ ]:
##result # n=6

In [19]:
##result # n=7

       Logistic      SVMl     SVMnl       KNN     Naive  Decision    Random
RF     0.899761  0.890215  0.887828  0.880668  0.871122  0.856802  0.890215
DT     0.892601  0.863962  0.880668  0.875895  0.854415  0.854415  0.887828
SVM    0.871122  0.863962  0.863962  0.861575  0.804296  0.828162  0.875895
XGB    0.890215  0.863962  0.892601  0.880668  0.840095  0.885442  0.880668
LogR   0.863962  0.863962  0.863962  0.875895  0.842482  0.806683  0.871122
Ridge  0.866348  0.863962  0.866348  0.866348  0.797136  0.866348  0.861575

In [24]:
#result # n=30

       Logistic      SVMl     SVMnl       KNN     Naive  Decision    Random
RF     0.940334  0.940334  0.909308  0.880668  0.749403  0.875895  0.897375
DT     0.935561  0.935561  0.916468  0.878282  0.787589  0.890215  0.904535
SVM    0.940334  0.933174  0.911695  0.878282  0.809069  0.871122  0.885442
XGB    0.945107  0.940334  0.923628  0.892601  0.675418  0.880668  0.902148
LogR   0.942721  0.942721  0.911695  0.878282   0.75895  0.868735  0.897375
Ridge  0.930788  0.940334  0.911695  0.883055  0.405728  0.887828  0.885442

In [29]:
##result # n=35

       Logistic      SVMl     SVMnl       KNN     Naive  Decision    Random
RF     0.935561  0.930788  0.911695  0.880668  0.689737  0.885442  0.899761
DT     0.937947  0.933174  0.914081  0.883055  0.424821  0.887828  0.897375
SVM    0.935561  0.928401  0.914081  0.875895  0.699284  0.880668  0.894988
XGB    0.937947  0.930788  0.914081  0.885442  0.680191  0.883055  0.899761
LogR   0.937947  0.933174  0.914081  0.875895  0.696897  0.863962  0.892601
Ridge  0.930788  0.930788  0.916468  0.894988  0.443914  0.887828  0.897375

In [ ]:
## On comparing with various n values for FeatureImportance, n=7 gives better result