In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("watson_healthcare_modified.csv")
df

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,3,Technical Degree,1,...,2,80,0,1,3,1,1,0,0,0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,3,Marketing,1,...,3,80,1,15,3,3,3,2,1,2
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,3,Life Sciences,1,...,4,80,0,1,0,4,1,0,0,0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,1,Life Sciences,1,...,3,80,1,21,3,3,21,6,11,8
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,2,Medical,1,...,2,80,0,9,5,2,8,7,0,7

In [3]:
##To check the Null values in dataset
df.isnull().sum()

EmployeeID                  0
Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
Shift                       0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [4]:
df.describe()

,EmployeeID,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1.676000e+03,1676.000000,1676.000000,1676.000000,1676.000000,1676.0,1676.000000,1676.000000,1676.000000,1676.000000,...,1676.000000,1676.0,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000
mean,1.456796e+06,36.866348,800.557876,9.221957,2.907518,1.0,2.714797,65.470167,2.724940,2.066826,...,2.718377,80.0,0.806086,11.338902,2.805489,2.766110,7.033413,4.264916,2.200477,4.135442
std,2.487486e+05,9.129126,401.594438,8.158118,1.025835,0.0,1.097534,20.207572,0.714121,1.113423,...,1.078162,0.0,0.855527,7.834996,1.288431,0.702369,6.098991,3.627456,3.229587,3.559662
min,1.025177e+06,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.235832e+06,30.000000,465.000000,2.000000,2.000000,1.0,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,1.464606e+06,36.000000,796.500000,7.000000,3.000000,1.0,3.000000,65.500000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,1.667992e+06,43.000000,1157.000000,14.000000,4.000000,1.0,4.000000,83.000000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000
max,1.886378e+06,60.000000,1499.000000,29.000000,5.000000,1.0,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [5]:
##To check how many duplicates in dataset
duplicate_count = df.duplicated().sum()
duplicate_count

0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeID                1676 non-null   int64
 1   Age                       1676 non-null   int64
 2   Attrition                 1676 non-null   object
 3   BusinessTravel            1676 non-null   object
 4   DailyRate                 1676 non-null   int64
 5   Department                1676 non-null   object
 6   DistanceFromHome          1676 non-null   int64
 7   Education                 1676 non-null   int64
 8   EducationField            1676 non-null   object
 9   EmployeeCount             1676 non-null   int64
 10  EnvironmentSatisfaction   1676 non-null   int64
 11  Gender                    1676 non-null   object
 12  HourlyRate                1676 non-null   int64
 13  JobInvolvement            1676 non-null   int64
 14  JobLevel                  1676 non-null   int64
 15  JobRole                   1676 non-null   object
 16  JobSatisfaction           1676 non-null   int64
 17  MaritalStatus             1676 non-null   object
 18  MonthlyIncome             1676 non-null   int64
 19  MonthlyRate               1676 non-null   int64
 20  NumCompaniesWorked        1676 non-null   int64
 21  Over18                    1676 non-null   object
 22  OverTime                  1676 non-null   object
 23  PercentSalaryHike         1676 non-null   int64
 24  PerformanceRating         1676 non-null   int64
 25  RelationshipSatisfaction  1676 non-null   int64
 26  StandardHours             1676 non-null   int64
 27  Shift                     1676 non-null   int64
 28  TotalWorkingYears         1676 non-null   int64
 29  TrainingTimesLastYear     1676 non-null   int64
 30  WorkLifeBalance           1676 non-null   int64
 31  YearsAtCompany            1676 non-null   int64
 32  YearsInCurrentRole        1676 non-null   int64
 33  YearsSinceLastPromotion   1676 non-null   int64
 34  YearsWithCurrManager      1676 non-null   int64
dtypes: int64(26), object(9)
memory usage: 458.4+ KB

In [7]:
## dropping unwanted columns
df=df.drop(['EmployeeCount','StandardHours','Over18','Education'],axis=1)

In [8]:
df.select_dtypes(include=['object', 'category']).columns.tolist()

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'OverTime']

In [9]:
# Performing Exploratory Data Analysis

df

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,Technical Degree,3,Male,...,3,2,0,1,3,1,1,0,0,0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,Marketing,3,Female,...,3,3,1,15,3,3,3,2,1,2
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,Life Sciences,4,Female,...,3,4,0,1,0,4,1,0,0,0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,Life Sciences,4,Female,...,3,3,1,21,3,3,21,6,11,8
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,Medical,1,Female,...,3,2,0,9,5,2,8,7,0,7

In [10]:
## UNIVARIATE ANALYSIS

In [11]:
from UnivariateFile import UnivariateClass as uv
Quan,Qual=uv.QuanQual(df)
Quan

['EmployeeID',
 'Age',
 'DailyRate',
 'DistanceFromHome',
 'EnvironmentSatisfaction',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'Shift',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [12]:
df[Quan].isnull().sum()
df[Quan].drop('EmployeeID',axis=1)

,Age,DailyRate,DistanceFromHome,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,94,3,2,4,5993,19479,...,3,1,0,8,0,1,6,4,0,5
1,49,279,8,3,61,2,2,2,5130,24907,...,4,4,1,10,3,3,10,7,1,7
2,37,1373,2,4,92,2,1,3,2090,2396,...,3,2,0,7,3,3,0,0,0,0
3,33,1392,3,4,56,3,1,3,2909,23159,...,3,3,0,8,3,3,8,7,3,0
4,27,591,2,1,40,3,1,2,3468,16632,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,26,471,24,3,66,1,1,4,2340,23213,...,3,2,0,1,3,1,1,0,0,0
1672,46,1125,10,3,94,2,3,4,9071,11563,...,3,3,1,15,3,3,3,2,1,2
1673,20,959,1,4,83,2,1,2,2836,11757,...,3,4,0,1,0,4,1,0,0,0
1674,39,466,1,4,65,2,4,4,12742,7060,...,3,3,1,21,3,3,21,6,11,8
1675,27,511,2,1,89,4,2,3,6500,26997,...,3,2,0,9,5,2,8,7,0,7

In [13]:
descriptive=uv.univariate_descriptive(df,Quan)

descriptive[Quan].drop('EmployeeID',axis=1)

,Age,DailyRate,DistanceFromHome,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Mean,36.866348,800.557876,9.221957,2.714797,65.470167,2.72494,2.066826,2.738663,6516.51253,14287.01969,...,3.150358,2.718377,0.806086,11.338902,2.805489,2.76611,7.033413,4.264916,2.200477,4.135442
Median,36.0,796.5,7.0,3.0,65.5,3.0,2.0,3.0,4899.0,14269.5,...,3.0,3.0,1.0,10.0,3.0,3.0,5.0,3.0,1.0,3.0
Mode,35,691,2,3,48,3,1,4,2340,4223,...,3,3,0,10,2,3,5,2,0,2
Q1-25%,30.0,465.0,2.0,2.0,48.0,2.0,1.0,2.0,2928.25,7993.0,...,3.0,2.0,0.0,6.0,2.0,2.0,3.0,2.0,0.0,2.0
Q2-50%,36.0,796.5,7.0,3.0,65.5,3.0,2.0,3.0,4899.0,14269.5,...,3.0,3.0,1.0,10.0,3.0,3.0,5.0,3.0,1.0,3.0
Q3-75%,43.0,1157.0,14.0,4.0,83.0,3.0,3.0,4.0,8380.25,20462.0,...,3.0,4.0,1.0,15.0,3.0,3.0,10.0,7.0,3.0,7.0
99%,58.0,1482.75,29.0,4.0,100.0,4.0,5.0,4.0,19616.25,26704.0,...,4.0,4.0,3.0,35.0,6.0,4.0,30.25,15.0,14.0,14.0
Q4-100%,60.0,1499.0,29.0,4.0,100.0,4.0,5.0,4.0,19999.0,26999.0,...,4.0,4.0,3.0,40.0,6.0,4.0,40.0,18.0,15.0,17.0
IQR,13.0,692.0,12.0,2.0,35.0,1.0,2.0,2.0,5452.0,12469.0,...,0.0,2.0,1.0,9.0,1.0,1.0,7.0,5.0,3.0,5.0
1.5rule,19.5,1038.0,18.0,3.0,52.5,1.5,3.0,3.0,8178.0,18703.5,...,0.0,3.0,1.5,13.5,1.5,1.5,10.5,7.5,4.5,7.5
Lesser_range,10.5,-573.0,-16.0,-1.0,-4.5,0.5,-2.0,-1.0,-5249.75,-10710.5,...,3.0,-1.0,-1.5,-7.5,0.5,0.5,-7.5,-5.5,-4.5,-5.5
Greater_range,62.5,2195.0,32.0,7.0,135.5,4.5,6.0,7.0,16558.25,39165.5,...,3.0,7.0,2.5,28.5,4.5,4.5,20.5,14.5,7.5,14.5
Min,18,102,1,1,30,1,1,1,1009,2094,...,3,1,0,0,0,1,0,0,0,0
Max,60,1499,29,4,100,4,5,4,19999,26999,...,4,4,3,40,6,4,40,18,15,17
kurtosis,-0.42809,-1.201299,-0.25171,-1.218306,-1.199436,0.239806,0.38263,-1.213537,0.978679,-1.226464,...,1.836813,-1.173564,0.315614,0.823952,0.473374,0.471689,3.714953,0.468434,3.530137,0.076017
skew,0.419614,0.003889,0.953314,-0.313217,-0.008805,-0.487887,1.026815,-0.347154,1.3678,0.014844,...,1.958219,-0.309785,0.949235,1.098286,0.535139,-0.570576,1.722257,0.904216,1.970435,0.806627
variance,83.340933,161278.092768,66.554885,1.204581,408.345975,0.509969,1.239711,1.218827,22358301.990888,50963290.449164,...,0.127827,1.162432,0.731927,61.387166,1.660053,0.493322,37.197689,13.158434,10.430233,12.671197
std,9.129126,401.594438,8.158118,1.097534,20.207572,0.714121,1.113423,1.104005,4728.456618,7138.857783,...,0.357529,1.078162,0.855527,7.834996,1.288431,0.702369,6.098991,3.627456,3.229587,3.559662

In [14]:
## Finding the outliers
lesser_outlier,greater_outlier=uv.Identify_Outliers(descriptive,Quan)
lesser_outlier,greater_outlier

(['TrainingTimesLastYear'],
 ['MonthlyIncome',
  'NumCompaniesWorked',
  'PerformanceRating',
  'Shift',
  'TotalWorkingYears',
  'TrainingTimesLastYear',
  'YearsAtCompany',
  'YearsInCurrentRole',
  'YearsSinceLastPromotion',
  'YearsWithCurrManager'])

In [15]:
#replacing outliers with outlier range values
uv.replace_outliers(df,descriptive,lesser_outlier,greater_outlier)

/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]<descriptive[columnname]["Lesser_range"]]=descriptive[columnname]["Lesser_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/ML Capstone Project/2.Data Preprocessing/UnivariateFile.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]

In [16]:
df

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,Life Sciences,2,Female,...,3,1,0.0,8.0,0.5,1,6.0,4.0,0.0,5.0
1,1200302,49,No,Travel_Frequently,279,Maternity,8,Life Sciences,3,Male,...,3,4,1.0,10.0,3.0,3,10.0,7.0,1.0,7.0
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,Other,4,Male,...,3,2,0.0,7.0,3.0,3,0.0,0.0,0.0,0.0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,Life Sciences,4,Female,...,3,3,0.0,8.0,3.0,3,8.0,7.0,3.0,0.0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,Medical,1,Male,...,3,4,1.0,6.0,3.0,3,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,Yes,Travel_Rarely,471,Neurology,24,Technical Degree,3,Male,...,3,2,0.0,1.0,3.0,1,1.0,0.0,0.0,0.0
1672,1152327,46,No,Travel_Rarely,1125,Cardiology,10,Marketing,3,Female,...,3,3,1.0,15.0,3.0,3,3.0,2.0,1.0,2.0
1673,1812428,20,No,Travel_Rarely,959,Maternity,1,Life Sciences,4,Female,...,3,4,0.0,1.0,0.5,4,1.0,0.0,0.0,0.0
1674,1812429,39,No,Travel_Rarely,466,Neurology,1,Life Sciences,4,Female,...,3,3,1.0,21.0,3.0,3,20.5,6.0,7.5,8.0
1675,1152329,27,No,Travel_Rarely,511,Cardiology,2,Medical,1,Female,...,3,2,0.0,9.0,4.5,2,8.0,7.0,0.0,7.0

In [17]:
## validating whether the outliers are replaced

descriptive=uv.univariate_descriptive(df,Quan)

lesser_outlier,greater_outlier=uv.Identify_Outliers(descriptive,Quan)
lesser_outlier,greater_outlier

([], [])

In [18]:
## Frequency, Relative_frequency, cummulative relative frequency##

freqtable=uv.freqtable(df,"TotalWorkingYears")
freqtable

    Uniq_values  Frequency  Rel_Frequency  Cum_Frequency
0          10.0        233       7.766667       7.766667
1           6.0        140       4.666667      12.433333
2           8.0        123       4.100000      16.533333
3           9.0        108       3.600000      20.133333
4           5.0        100       3.333333      23.466667
5           1.0         94       3.133333      26.600000
6           7.0         88       2.933333      29.533333
7          28.5         75       2.500000      32.033333
8           4.0         70       2.333333      34.366667
9          12.0         51       1.700000      36.066667
10          3.0         50       1.666667      37.733333
11         15.0         47       1.566667      39.300000
12         16.0         40       1.333333      40.633333
13         17.0         40       1.333333      41.966667
14         21.0         39       1.300000      43.266667
15         11.0         39       1.300000      44.566667
16         13.0         39       1.300000      45.866667
17          2.0         36       1.200000      47.066667
18         14.0         35       1.166667      48.233333
19         20.0         34       1.133333      49.366667
20         18.0         30       1.000000      50.366667
21         23.0         27       0.900000      51.266667
22         22.0         25       0.833333      52.100000
23         19.0         25       0.833333      52.933333
24         24.0         22       0.733333      53.666667
25         25.0         17       0.566667      54.233333
26         28.0         16       0.533333      54.766667
27         26.0         15       0.500000      55.266667
28          0.0         11       0.366667      55.633333
29         27.0          7       0.233333      55.866667

In [19]:
Qual

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'OverTime']

In [20]:
## Converting Qual into Numerical columns

#to convert non numerical into numerical data
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False, drop='first', dtype=int)
encoded_array = encoder.fit_transform(df[['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','OverTime']])

In [21]:
#  Get clean names for the new columns and create a DataFrame
columns_to_encode = ['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','OverTime']
encoded_column_names = encoder.get_feature_names(columns_to_encode)
encoded_df = pd.DataFrame(encoded_array, columns=encoded_column_names)

# Merge back into the original dataset and drop the old raw text columns
# We use .concat() along axis=1 to join them side-by-side
final_df = pd.concat([df, encoded_df], axis=1).drop(columns=['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','OverTime'])
final_df

,EmployeeID,Age,Attrition,DailyRate,DistanceFromHome,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,EducationField_Other,EducationField_Technical Degree,Gender_Male,JobRole_Administrative,JobRole_Nurse,JobRole_Other,JobRole_Therapist,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,1313919,41,No,1102,1,2,94,3,2,4,...,0,0,0,0,1,0,0,0,1,1
1,1200302,49,No,279,8,3,61,2,2,2,...,0,0,1,0,0,1,0,1,0,0
2,1060315,37,Yes,1373,2,4,92,2,1,3,...,1,0,1,0,1,0,0,0,1,1
3,1272912,33,No,1392,3,4,56,3,1,3,...,0,0,0,0,0,1,0,1,0,1
4,1414939,27,No,591,2,1,40,3,1,2,...,0,0,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1671,1117656,26,Yes,471,24,3,66,1,1,4,...,0,1,1,0,1,0,0,0,1,1
1672,1152327,46,No,1125,10,3,94,2,3,4,...,0,0,0,0,1,0,0,1,0,1
1673,1812428,20,No,959,1,4,83,2,1,2,...,0,0,0,0,0,1,0,0,1,0
1674,1812429,39,No,466,1,4,65,2,4,4,...,0,0,0,0,0,0,1,1,0,0
1675,1152329,27,No,511,2,1,89,4,2,3,...,0,0,0,0,1,0,0,0,1,0

In [22]:
final_df.to_csv("preprocessed.csv", index=False)